### ISSUE TITLE
Proiectul este viu?

### ISSUE THREAD

**Issue by AltairGaruda** [ciocan/sicap.ai#20]
Doresc sa fac niste propuneri pentru claritate si interpretare date.

Mersi

**Comment by ciocan** [comment]
Salut, nu prea am mai avut timp de proiect in ultimul timp.
Dar este in picioare si functioneaza ok.

Orice propunere este bine venita.

**Comment by orlat84** [comment]
Ai timp de un chat pe marginea proiectului?
Eu am http://data.g4d.ro poate le putem unifica
