### ISSUE TITLE
Blocare cautare la 24.11.2022

### ISSUE THREAD

**Issue by Bue420** [ciocan/sicap.ai#24]
Buna seara ! Incerc sa iau legatura cu cineva din admin . Platforma a ramas blocata la data de 24.11.2022 in ceea ce priveste ORICE alta forma de atribuire mai putin contractele directe . Singura mea explicatie este ca cineva a blocat intentionat cautarile la data de 24.11.2022 , inutil de altfel , ptr ca nu au disparut in eter … Am incercat si cu cei de la Termene.ro , dar degeaba , de vreo 3 ori in ultimele 10 zile . Am un contract cu platforma de aprox 5500 lei / an . Sunt dispus sa va ofer sprijin financiar , doar sa functioneze macar ca inainte , cu bug-urile aferente . 
Multumesc ! 
Silviu Pintea  /

**Comment by uniformis** [comment]
salut! hai sa ne auzim la harvey @licitatii-publice.ro
